name: The_chronicler
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  cached_network_image: ^3.4.0
  mobile_scanner: ^7.2.0
  http: ^1.2.0
  url_launcher: ^6.2.0
  fl_chart: ^1.2.0
  share_plus: ^13.1.0
  google_fonts: ^8.1.0
  palette_generator: ^0.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.ttf

flutter_launcher_icons:
  ios: true
  image_path: "assets/app_icon.jpg"
  remove_alpha_ios: true