// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJeP6RyP-bW1_m5tBn_8bdHcS7oV7X_UU',
    appId: '1:227755250375:web:4614fbd8580bd64176e4e2',
    messagingSenderId: '227755250375',
    projectId: 'vinyl-hube-9383f',
    authDomain: 'vinyl-hube-9383f.firebaseapp.com',
    storageBucket: 'vinyl-hube-9383f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBweErBGGQolgGgku5l2wBDvmZLt3FIDYw',
    appId: '1:227755250375:android:b7a6c58d08176c3176e4e2',
    messagingSenderId: '227755250375',
    projectId: 'vinyl-hube-9383f',
    storageBucket: 'vinyl-hube-9383f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPW-LPWrfNYrl_3ZhG8_Ai-8Lgy1yAdrw',
    appId: '1:227755250375:ios:56db29f94c8f5dd476e4e2',
    messagingSenderId: '227755250375',
    projectId: 'vinyl-hube-9383f',
    storageBucket: 'vinyl-hube-9383f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPW-LPWrfNYrl_3ZhG8_Ai-8Lgy1yAdrw',
    appId: '1:227755250375:ios:56db29f94c8f5dd476e4e2',
    messagingSenderId: '227755250375',
    projectId: 'vinyl-hube-9383f',
    storageBucket: 'vinyl-hube-9383f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJeP6RyP-bW1_m5tBn_8bdHcS7oV7X_UU',
    appId: '1:227755250375:web:8803582405ecff6176e4e2',
    messagingSenderId: '227755250375',
    projectId: 'vinyl-hube-9383f',
    authDomain: 'vinyl-hube-9383f.firebaseapp.com',
    storageBucket: 'vinyl-hube-9383f.firebasestorage.app',
  );
}
